name: tennis-prediction
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - pip:
      - gradio==4.44.0
      - huggingface_hub==0.24.6